#!/bin/sh -e

if [ "$1" = "upgrade" -o "$1" = "remove" ]; then
  update-alternatives --remove lockmail /usr/bin/lockmail.maildrop
  update-alternatives --remove maildirmake /usr/bin/maildirmake.maildrop
  update-alternatives --remove deliverquota /usr/sbin/deliverquota.maildrop
  update-alternatives --remove maildir.5.gz /usr/share/man/man5/maildir.maildrop.5.gz
  update-alternatives --remove maildirquota.7.gz /usr/share/man/man7/maildirquota.maildrop.7.gz
  update-alternatives --remove makedat /usr/bin/makedat.maildrop
fi

#DEBHELPER#

exit 0
